# Generated by Django 4.1.3 on 2022-11-24 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name_plural': '1. Admin'},
        ),
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name_plural': '10.Carousel'},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': '7.Cart'},
        ),
        migrations.AlterModelOptions(
            name='cartproduct',
            options={'verbose_name_plural': '8.Cart Product'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '3. Category'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': '2. Customer'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': '9.Order'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '5. Products'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name_plural': '6.Product Image'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': '11.Review'},
        ),
    ]
